Repository wimpysworld/umpc-ubuntu, pull requests merged in 2022-10, with the labels that each got.

#46 Remove extra "a" before "bespoke". Replace "The run" by "Then run"
  README.md
Labels: hacktoberfest-accepted, documentation

#45 Fix link to "Ubuntu MATE images for the UMPCs" page
  README.md
Labels: hacktoberfest-accepted, documentation

#40 Fix GPD P3 stylus
  data/99-gpd-pocket3-touch.rules
Labels: bug, hacktoberfest-accepted

#44 micropc: Add Sino Wealth Mouse device
  data/80-gpd-micropc-trackpoint.conf
Labels: enhancement, hacktoberfest-accepted

#43 respin: Install squashfs-tools when needed
  umpc-ubuntu-respin.sh
Labels: enhancement, hacktoberfest-accepted
